[package]
name = "print_user_group"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
custom_debug_derive = "0.5.1"
once_cell = "1.17.1"
